### ISSUE TITLE
Getting special pokemon sprites (shiny/back/female) requires manual folder creation

### ISSUE THREAD

**Issue by AtomToast** [PokeAPI/pokebase#11]
If you want to access the different sprites of a pokemon for example by using:
`p = pb.pokemon_sprite("back/3")`
(same with using api.lookup_sprite and SpriteResource)
You'll get a "FileNotFoundError" unless you manually create the "back" folder inside the .cache/pokebase/sprite/pokemon folder

**Comment by GregHilmes** [comment]
Closed by #21, new release can be downloaded with pip.
