### ISSUE TITLE
Can you please push the code being deployed from PyPI

### ISSUE THREAD

**Issue by macgregor** [PokeAPI/pokebase#15]
I have to go into site-packages to look at where some things have moved, please push whatever you have to master or at least to another branch on here if you dont want to do that for some reason. It seems weird that you are releasing code for people to install when the source isnt up.

Edit: or is master ahead of pypi? theres no 1.2.0 tag, in any case its confusing what state things are in. I'd appreciate it if you took a few minutes to push what you have to github

**Comment by GregHilmes** [comment]
I'm not quite sure what happened, thank you for bringing this to my attention. master should be ahead of PyPI, but I'm not sure where the 1.2.0 tag went missing.

I probably missed tagging it while in the process of rewriting the wrapper. To further the difficulty, I haven't worked on `pokebase` in while.

I'll look into this soon and push updates to GitHub/PyPI as needed. I'll post back here when that happens.

**Comment by GregHilmes** [comment]
pokebase version 1.2.0 was commit 3e4655c, but I apparently never released a tag for that. master is ahead, and contains all of my changes to date. I'll push a tag for that commit today.

**Comment by GregHilmes** [comment]
Fixed. Tag can be found [here](https://github.com/PokeAPI/pokebase/releases/tag/1.2.0).
