### ISSUE TITLE
Root endpoint support

### ISSUE THREAD

**Issue by C-Garza** [PokeAPI/pokebase#24]
I noticed root endpoints don't work for endpoints that don't have `name` properties for their objects, such as `/machine`. I talk about this in [this issue at pokepy](https://github.com/PokeAPI/pokepy/issues/64#issuecomment-739669956), but I'll state it again. The `/machine` endpoint returns this:
```
results: [
  0: {
    url: "https://pokeapi.co/api/v2/machine/1/"
  },
  ...
]
```
while the `/pokemon` endpoint returns this:
```
results: [
  0: {
    name: "bulbasaur",
    url: "https://pokeapi.co/api/v2/pokemon/1/"
  },
  ...
]
```
Because there's no `name` property, it returns None for the name here in the [APIResource class](https://github.com/PokeAPI/pokebase/blob/236c7551760b340b7f7c55466d0b5c4d8901d8a7/pokebase/interface.py#L90-L93).

I think I managed to fix the issue by adding this conditional after those lines:
```
if name == None:
  self.__dict__.update({'name': id_})
```
Should I open a pull request for this then?

**Comment by Davidy22** [comment]
I got a fix for this merged, does latest work for you now?

**Comment by GregHilmes** [comment]
Closed due to no response.
