### ISSUE TITLE
Unable to get Pokemon evolution Chain

### ISSUE THREAD

**Issue by Indiance** [PokeAPI/pokebase#28]
How to recreate problem:
-> Install pokebase
-> char = pokebase.pokemon_species("charmander")
-> char.evolution_chain should return evolution-chain-charmander but it returns evolution-chain-none

How to fix this?

**Comment by Davidy22** [comment]
I have the fix for this among some other updates in a fork I made, for the time being you can clone my copy and use that until I get that and a bunch of other nonsense I've been doing pulled into the main branch

https://github.com/Davidy22/pokebase

**Comment by Indiance** [comment]
Ah I see, thank you

**Comment by GregHilmes** [comment]
This should be fixed in Pokebase by #29 now, can you confirm @Indiance ?

**Comment by Indiance** [comment]
Yup It works thanks
