### ISSUE TITLE
Python 3.11 vs 3.6 possible to update to run on more recent version of Python?

### ISSUE THREAD

**Issue by Lumb3rJaX** [PokeAPI/pokebase#47]
I use Python for a few personal projects and and they all require a more recent version of Python than 3.6 is it possible or is there a way to update the API locally so that it will work with the 3.11v of python? are there plans in place for this repo to get updated to a newer version already?

**Comment by HumanBot000** [comment]
I hope to

**Comment by DahanDv** [comment]
@Naramsim, I think this one can be closed as well.

**Comment by HumanBot000** [comment]
Why?

Is py3.11 now supported?

**Comment by DahanDv** [comment]
@HumanBot000  Indeed bud, all the way up to 3.12.0 :)
