### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokebase#53]
Hello @DahanDv @GregHilmes , would it be possible for you to check possible dependencies updates? 

Many thanks!

**Comment by DahanDv** [comment]
@Naramsim I'll see what can be bumped and PR today. 
Please assign it to me :)

**Comment by Naramsim** [comment]
Yay! Super! Many thanks!

**Comment by DahanDv** [comment]
@Naramsim While working on this, I found that keeping support for 3.6-7 is a pain.
Before I tackle this one for good, I wanted to make sure you wish to keep supporting these.
Many have been dropping support for anything under py 3.8 for quite some time. 

If you decide to drop support for 3.6-7, this will make our lives much simpler and enable us to use modern tools for libraries to project management tools.

Let me know :)

**Comment by Naramsim** [comment]
Ok let's do that! So you can bump the package version and drop the support 💪

**Comment by DahanDv** [comment]
@Naramsim OK!
I'll update the existing PR, so please wait until I mention you in the PR's comments so you it's ready :)
