### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokebase#56]
@GregHilmes Hi! I wanted to upload a new package to Pypi. 

And I saw it's under your name there. Are you willing to transfer the repo to an organization I'm currently creating? So we'll be able to push new packages. Or If you're not active anymore maybe you can hand over the project to https://pypi.org/user/pokeapi/. 

Let me know what's the best :)

**Comment by GregHilmes** [comment]
If I am understanding the PyPI workflow correctly, either I need to be added to the organization as a manager and then I can initiate the transfer, or possibly someone else who is a manager can be added as a contributor to `pokebase` and then they can initiate the transfer.

**Comment by Naramsim** [comment]
Pypi hasn't yet replied to my request. 

If you're still active on GitHub you could deploy the new version to pypi under your package 🙂

If you want you could also invite the pokeapi user to be a contributor

**Comment by Naramsim** [comment]
Thanks @GregHilmes for adding the pokeapi user to your opackage
